import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  header: {
    width: '100%',
    height: 200,
    borderBottomLeftRadius: 80,
    borderBottomRightRadius: 80,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 30,
  },
  logo: {
    color: '#fff',
    fontSize: 28,
    fontWeight: 'bold',
    letterSpacing: 1,
  },
  title: {
    fontSize: 28,
    fontWeight: '600',
    color: '#333',
    marginTop: 30,
    marginBottom: 20,
    textAlign: 'center',
  },
  inputContainer: {
    width: '80%',
  },
  input: {
    color: '#000',
    backgroundColor: '#f2f2f2',
    borderRadius: 25,
    paddingHorizontal: 20,
    height: 50,
    marginBottom: 10,
    fontSize: 16,
    position: 'relative',
    borderWidth: 0,
  },
  passwordContainer: {
    position: 'absolute',
    right: 15,
    top: 80,
  },
  errorText: {
    color: 'red',
    fontSize: 12,
    alignSelf: 'flex-end',
  },
  options: {
    width: '80%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 10,
  },
  remember: {
    fontSize: 13,
    color: '#555',
    marginLeft: 8,
  },
  forget: {
    fontSize: 13,
    color: '#8E2DE2',
    fontWeight: '500',
  },
  buttonBorder: {
    width: '80%',
    borderRadius: 25,
    padding: 2,
    marginTop: 10,
  },
  loginButton: {
    backgroundColor: '#fff',
    borderRadius: 25,
    alignItems: 'center',
    paddingVertical: 12,
  },
  loginText: {
    color: '#4b0079ff',
    fontSize: 18,
    fontWeight: '600',
  },
  signupText: {
    marginTop: 20,
    color: '#555',
    fontSize: 15,
  },
  signupLink: {
    color: '#8E2DE2',
    fontWeight: 'bold',
  },
  orText: {
    marginTop: 10,
    color: '#aaa',
    fontSize: 15,
  },
  socialContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    width: '60%',
    borderRadius: 30,
    marginTop: 12,
  },
  iconBg: {
    padding: 10,
    borderRadius: 50,
  },
  bottomText: {
    marginTop: 15,
    color: '#888',
    fontSize: 13,
  },
  searchContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f1f1f1',
    borderRadius: 8,
    paddingHorizontal: 10,
    marginRight: 16,
  },
  topBar: {
    justifyContent: 'space-between',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
  },
  searchInput: {
    padding: 8,
    color: '#000',
  },
  productImg: {
    width: 'auto',
    height: 100,
    backgroundColor: '#ebebebff',
    borderRadius: 10,
    objectFit: 'cover',
  },
  products: {
    flex: 1,
    paddingHorizontal: 12,
    alignSelf: 'flex-start',
    borderBottomWidth: 1,
    borderBottomColor: '#ccc',
    marginBottom: 8,
    borderRadius: 16,
  },
  category: {
    color: '#000',
    fontSize: 16,
    alignSelf: 'flex-start',
    fontWeight: '800',
  },
  card: {
    width: 120,
    padding: 8,
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 8,
    marginVertical: 8,
    marginRight: 10,
  },
  productDetails: {
    marginTop: 8,
  },
  details: {
    color: '#000',
    textAlign: 'center',
    lineHeight: 25,
  },
  addCart: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 10,
  },
  quantityController: {
    fontSize: 16,
    color: '#000',
    padding: 4,
    paddingHorizontal: 12,
    backgroundColor: '#e88000ff',
    borderRadius: 60,
  },
  addCartText: {
    marginTop: 10,
    alignItems: 'center',
    backgroundColor: '#e88000ff',
    borderRadius: 40,
    paddingVertical: 6,
    fontWeight: '900',
  },
  noStock: {
    color: 'red',
    marginTop: 10,
    textAlign: 'center',
    backgroundColor: '#e1e1e1ff',
    borderRadius: 40,
    paddingVertical: 6,
  },
  bagButton: {
    position: 'relative',
    right: 5,
  },
  cartBadge: {
    position: 'absolute',
    left: 12,
    bottom: 10,
  },
  cartBadgeText: {
    backgroundColor: 'red',
    color: '#fff',
    borderRadius: 8,
    paddingHorizontal: 5,
    fontSize: 10,
    fontWeight: 'bold',
  },
  cartItem: {
    padding: 12,
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 8,
    marginVertical: 6,
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  cartDetail: {
    width: 200,
    justifyContent: 'center',
    alignItems: 'center',
  },
  centerItems: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 30,
  },
  emptyCart: {
    color: '#000',
    fontSize: 20,
    fontWeight: 'bold',
    letterSpacing: 1,
    borderBottomWidth: 1,
    borderBottomColor: '#000',
  },
  footerWrapper: {
    position: 'absolute',
    bottom: 20,
    left: 20,
    right: 20,
  },
  footer: {
    borderRadius: 30,
    padding: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  leftSection: {
    flexDirection: 'column',
  },
  totalItems: {
    color: '#fff',
    fontSize: 14,
    opacity: 0.8,
  },
  totalPrice: {
    color: '#fff',
    fontSize: 28,
    fontWeight: 'bold',
    marginTop: 4,
  },
  checkoutButton: {
    backgroundColor: '#fff',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 25,
  },
  checkoutText: {
    color: '#0044CC',
    fontWeight: 'bold',
    fontSize: 15,
  },
});
